BASE <http://www.m0ep.de/socc/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX siocs: <http://rdfs.org/sioc/services#>
PREFIX siocsa: <http://www.m0ep.de/sioc/services/auth#>
PREFIX socccfg: <http://www.m0ep.de/socc/config#>
prefix waa: <http://purl.oclc.org/NET/WebApiAuthentication#>

INSERT DATA {

    # Service Canvas LMS 
    <service/canvas-test> a siocs:Service;
        siocs:serviceEndoint <https://canvas.instructure.com>;
        siocs:serciceDefinition "Canvas LMS Test Server" .

    # Service Moodle

    <service/moodle-test> a siocs:Service;
        siocs:serviceEndoint <http://localhost/moodle>;
        siocs:serciceDefinition "Moodle LMS Test Server" .

    # Service Google Plus

    <service/googleplus> a siocs:Service;
        siocs:serviceEndoint <https://plus.google.com>;
        siocs:serciceDefinition "Google Plus";
        siocsa:serviceAuthentication <service/googleplus/oauth> .

    <service/googleplus/oauth> a waa:OAuth;
        siocsa:credentials <service/googleplus/oauth/clientid>;
        siocsa:serviceAuthentication <service/googleplus/oauth/clientsecret> .

    <service/googleplus/oauth/clientid> a siocsa:ClientId;
        rdf:value "733024832603-patciplam4cqq0dnv7a5qdhuq262n6ia.apps.googleusercontent.com".

    <service/googleplus/oauth/clientsecret> a siocsa:ClientSecret;
        rdf:value "LckucP4MA1jJsZQKjk9okhAu".

    # Service Facebook

    <service/facebook> a siocs:Service;
        siocs:serviceEndoint <https://facebook.com>;
        siocs:serciceDefinition "Facebook";
        siocsa:serviceAuthentication <service/facebook/oauth> .

    <service/facebook/oauth> a waa:OAuth;
        siocsa:credentials <service/facebook/oauth/clientid>;
        siocsa:serviceAuthentication <service/facebook/oauth/clientsecret> .

    <service/facebook/oauth/clientid> a siocsa:ClientId;
        rdf:value "218182098322396".

    <service/facebook/oauth/clientsecret> a siocsa:ClientSecret;
        rdf:value "f4ed27b621c0f6476c2741f7cf9c4dc5".

    # Service Youtube

    <service/youtube> a siocs:Service;
        siocs:serviceEndoint <https://youtube.com>;
        siocs:serviceDefinition "Youtube";
        siocsa:serviceAuthentication <service/youtube/webapi> .

    <service/youtube/webapi> a siocsa:WebApi;
        siocsa:credentials <service/youtube/webapi/apikey>.

    <service/youtube/webapi/apikey> a waa:APIKey;
        rdf:value "AI39si48dEjhAE9RrY6w1HnlmyrUUTDt-xssOKkEEcpOIMD1gFcQ-0Xv40YNl-H1MxFzGzbHih4ootWo1cRrPH9gV-5UdazEbQ".

    ##########################################################

    # User SOCC Bot

    <user/socc-bot> a foaf:Person;
        foaf:nick "socc-bot";
        foaf:name "Socc Bot";
        foaf:account <user/socc-bot/moodle>;
        foaf:account <user/socc-bot/canvaslms>;
        foaf:account <user/socc-bot/youtube>.

    # User SOCC Bot Account Moodle

    <user/socc-bot/moodle> a sioc:UserAccount;
        foaf:accountName "socc-bot";
        foaf:accountServiceHomepage <http://localhost/~florian/moodle>;
        siocsa:accountAuthentication <user/socc-bot/moodle/direct> .

    <user/socc-bot/moodle/direct> a waa:Direct;
        siocsa:credentials <user/socc-bot/moodle/direct/username>;
        siocsa:credentials <user/socc-bot/moodle/direct/password> .

    <user/socc-bot/moodle/direct/username> a waa:Username;
        rdf:value "socc-bot" .

    <user/socc-bot/moodle/direct/password> a waa:Password;
        rdf:value "socc-bot_pwd" .

    # User SOCC Bot Account Canvas LMS

    <user/socc-bot/canvaslms> a sioc:UserAccount;
        foaf:accountName "3478501";
        foaf:accountServiceHomepage <https://canvas.instructure.com>;
        siocsa:accountAuthentication <user/socc-bot/canvaslms/oauth> .

    <user/socc-bot/canvaslms/oauth> a waa:OAuth;
        siocsa:credentials <user/socc-bot/canvaslms/oauth/accesstoken> .

    <user/socc-bot/canvaslms/oauth/accesstoken> a siocsa:AccessToken;
        rdf:value "7~LUpV7B3lJYadvZ2sHlpJiTcyJ6HaduVb3Ho8YjBNXSdIE4AEFzLFfORcOHRHh1fU" .

    # User SOCC Bot Account Youtube

    <user/socc-bot/youtube> a sioc:UserAccount;
        foaf:accountName "tkhiwis@gmail.com";
        foaf:accountServiceHomepage <http://www.youtube.com>;
        siocsa:accountAuthentication <user/socc-bot/youtube/direct>.

    <user/socc-bot/youtube/direct> a waa:Direct;
        siocsa:credentials <user/socc-bot/youtube/direct/username>;
        siocsa:credentials <user/socc-bot/youtube/direct/password>.

    <user/socc-bot/youtube/direct/username> a waa:Username;
        rdf:value "tkhiwis@gmail.com".

    <user/socc-bot/youtube/direct/password> a waa:Password;
        rdf:value "turing123".


    ##########################################################

    # User Florian


    <user/florian> a foaf:Person;
        foaf:nick "m0ep";
        foaf:name "Florian Müller";
        foaf:account <user/florian/canvas>;
        foaf:account <user/florian/googleplus>; 
        foaf:account <user/florian/facebook>;
        foaf:account <user/florian/youtube>;
        foaf:account <user/florian/moodle>.

    # User Florian Account Canvas LMS

    <user/florian/canvas> a sioc:UserAccount;
        foaf:accountName "3457836";
        foaf:accountServiceHomepage <https://canvas.instructure.com>;
        siocsa:accountAuthentication <user/florian/canvas/oauth> .

    <user/florian/canvas/oauth> a waa:OAuth;
        siocsa:credentials <user/florian/canvas/oauth/accesstoken> .

    <user/florian/canvas/oauth/accesstoken> a siocsa:AccessToken;
        rdf:value "7~LUpV7B3lJYadvZ2sHlpJiTcyJ6HaduVb3Ho8YjBNXSdIE4AEFzLFfORcOHRHh1fU" .

    # User Florian Account Google Plus

    <user/florian/googleplus> a sioc:UserAccount;
        foaf:accountName "111006860599162359588";
        foaf:accountServiceHomepage <https://plus.google.com>;
        siocsa:accountAuthentication <user/florian/googleplus/oauth> .

    <user/florian/googleplus/oauth> a waa:OAuth;
        siocsa:credentials <user/florian/googleplus/oauth/accesstoken>;
        siocsa:credentials <user/florian/googleplus/oauth/refreshtoken> .

    <user/florian/googleplus/oauth/accesstoken> a siocsa:AccessToken;
        rdf:value "ya29.AHES6ZTQADJwz1jLzgACCny1r9A9u9SqjbeOm9JLm_RzvgEPER0" .

    <user/florian/googleplus/oauth/refreshtoken> a siocsa:RefreshToken;
        rdf:value "1/Qsc2kHvKM5g-t_GyrFIF54RvXmCMU5AM3ezxrHdRjBI" .

    # User Florian Account Youtube

    <user/florian/youtube> a sioc:UserAccount;
        foaf:accountName "m0eper";
        foaf:accountServiceHomepage <https://youtube.com>;
        siocsa:accountAuthentication <user/florian/youtube/direct> .

    <user/florian/youtube/direct> a waa:Direct;
        siocsa:credentials <user/florian/youtube/direct/username>;
        siocsa:credentials <user/florian/youtube/direct/password> .

    <user/florian/youtube/direct/username> a waa:Username;
        rdf:value "email.mufl" .

    <user/florian/youtube/direct/password> a waa:Password;
        rdf:value "email.mufl.net" .

    # User Florian Account Moodle

    <user/florian/moodle> a sioc:UserAccount;
        foaf:accountName "m0ep";
        foaf:accountServiceHomepage <http://localhost/~florian/moodle>;
        siocsa:accountAuthentication <user/florian/moodle/direct> .

    <user/florian/moodle/direct> a waa:Direct;
        siocsa:credentials <user/florian/moodle/direct/username>;
        siocsa:credentials <user/florian/moodle/direct/password> .

    <user/florian/moodle/direct/username> a waa:Username;
        rdf:value "m0ep" .

    <user/florian/moodle/direct/password> a waa:Password;
        rdf:value "m0eper" .

    ##########################################################

    # Connectors

    <connector/canvaslms-test> a socccfg:ConnectorConfig;
        socccfg:connectorClass "de.m0ep.socc.core.connector.canvaslms.CanvasLmsConnector";
        socccfg:id "canvaslms-test";
        socccfg:defaultUserAccount <user/socc-bot/canvaslms>;
        socccfg:service <service/canvas-test> .

    ##########################################################
}